#!/bin/bash

AWS_REGION=ap-southeast-2
AWS_ACCOUNT_ID=xxxxxxxxxxxx
IMAGE_NAME=helloworld
ECR_REPO_NAME=helloworld

ecr_repo=$(aws ecr describe-repositories --repository-name $ECR_REPO_NAME --region $AWS_REGION | jq '.repositories[].repositoryArn')
if [ -z $ecr_repo ]; then
    echo "---------Creating the ECR repo--------"
    aws ecr create-repository --repository-name $ECR_REPO_NAME --region $AWS_REGION
    echo ""
else
    echo ""
    echo "Image will be pushed to ECR repo : $ecr_repo"
    echo ""
fi

echo "---------Building the image-----------"
aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
docker build . -t $IMAGE_NAME
echo ""
echo "---------Pushing the image-----------"
docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
echo ""
echo "---------Deploying the image-----------"
kubectl apply -f ./deployment.yaml
echo ""
echo "---------Check the deployment-----------"
kubectl get deployments
echo ""
kubectl get pods
echo ""